# Site settings
title: Codingo Tuts
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Set of tutorials for developers, how to build smarter, faster and great applications. Tips and tricks from experienced developers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: codingo_me
github_username:  codingo-me

# Build settings
markdown: kramdown
